### ISSUE TITLE
Contact Form Integration Support

### ISSUE THREAD

**Issue by studentofcoding** [evercam/evercam-static#25]
Currently, WordPress has its own custom plugins to handle Form submission to Zoho CRM (which include dashboard submitted form)

It's non-existent on Storyblok and Nuxt ecosystem, thus we need to build a customized solution to 

- To capture contact form submitted 
- Show it on Zoho workspace

And this solution is out of scope.

**Comment by marcoherbst** [comment]
The Zoho in IFRAME solution seems good to me.
