### ISSUE TITLE
Properly use storyblok templates for all pages

### ISSUE THREAD

**Issue by yzdbg** [evercam/evercam-static#40]
Some pages are hardcoded and not using storyblok. Leading to the content not using storyblok templates and thus not being interactive/editable in storyblok. 

@studentofcoding Could you please make a list of the pages that are hardcoded and add them to the task list below : 

- [x]  /about page : https://github.com/evercam/evercam-static/blob/main/storyblok/pages/about/SectionAboutContainer.vue

**Comment by studentofcoding** [comment]
Noted @yzdbg

**Comment by studentofcoding** [comment]
> Some pages are hardcoded and not using storyblok. Leading to the content not using storyblok templates and thus not being interactive/editable in storyblok.
> 
> @studentofcoding Could you please make a list of the pages that are hardcoded and add them to the task list below :
> 
> * [ ]   /about page : https://github.com/evercam/evercam-static/blob/main/storyblok/pages/about/SectionAboutContainer.vue

This is the list : 
- About page,
- Thank you page,
- Brand,
- Partners,
- Contact,

**Comment by studentofcoding** [comment]
All pages are using Storyblok now @yzdbg
