### ISSUE TITLE
Move hard-coded strings to Storyblok

### ISSUE THREAD

**Issue by halimb** [evercam/evercam-static#52]
- [x] [storyblok/pages/features/SectionOtherFeatures.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/features/SectionOtherFeatures.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/homepage/SectionTellUs.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/homepage/SectionTellUs.vue) - Converted to using storybook
- [x] [storyblok/pages/contact/SectionSendUs.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/contact/SectionSendUs.vue)  - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/features/SectionOtherFeatures.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/features/SectionOtherFeatures.vue)  - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/contact/SectionContactUs.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/contact/SectionContactUs.vue)  - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/homepage/SectionSoftwareIntegration.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/homepage/SectionSoftwareIntegration.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/features/SectionSoftwareIntegrationCTA.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/features/SectionSoftwareIntegrationCTA.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/terms/SectionTerms.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/terms/SectionTerms.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/terms/SectionTerms.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/terms/SectionTerms.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/features/SectionAllFeatures.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/features/SectionAllFeatures.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/blogs/BlogsIndividual.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/blogs/BlogsIndividual.vue) - Refactored
- [x] [storyblok/pages/blogs/BlogCardIndividual.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/blogs/BlogCardIndividual.vue) - Refactored
- [x] [storyblok/pages/features/FeaturesIndividual.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/features/FeaturesIndividual.vue) - Refactored
- [x] [storyblok/pages/homepage/SectionRecentProjects.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/homepage/SectionRecentProjects.vue) - Refactored
- [x] [storyblok/pages/homepage/SectionRecentProjects.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/homepage/SectionRecentProjects.vue) - Refactored
- [x] [storyblok/pages/partners/SectionPartnerCard.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/partners/SectionPartnerCard.vue) - Already Storyblok component
- [x] [storyblok/pages/homepage/SectionSuccessStories.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/homepage/SectionSuccessStories.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/testimonials/SectionStoriesTestimonials.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/testimonials/SectionStoriesTestimonials.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/trust/SectionGDPR.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/trust/SectionGDPR.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/tutorials/SectionTutorialList.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/tutorials/SectionTutorialList.vue) - Converted to Storyblok
- [x] [storyblok/pages/tutorials/TutorialsIndividual.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/tutorials/TutorialsIndividual.vue) - Tidy up & Already on Storyblok
- [x] [storyblok/pages/projects/ProjectIndividual.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/projects/ProjectIndividual.vue) - Tidy up & Already on Storyblok
- [x] [storyblok/pages/testimonials/SectionStoriesTestimonials.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/testimonials/SectionStoriesTestimonials.vue) - Deleted, as it's already use Dynamic component
- [x] [storyblok/pages/about/SectionAboutContainer.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/about/SectionAboutContainer.vue) - Change to SectionMapContainer.vue & use Storyblok component
- [x] [/error.vue](https://github.com/evercam/evercam-static/blob/main/error.vue) - This is Nuxt way of handling 404 pages, in which not included on Storyblok, more about it here https://nuxt.com/docs/getting-started/error-handling#rendering-an-error-page
- [x] [storyblok/pages/brand/SectionBrandContent.vue](https://github.com/evercam/evercam-static/blob/main/storyblok/pages/brand/SectionBrandContent.vue) - It's fully Storyblok now

**Comment by studentofcoding** [comment]
The corresponding PR is in https://github.com/evercam/evercam-static/pull/54

**Comment by studentofcoding** [comment]
All done @halimb
